import type { ReactElement } from "react";
import type { TokenNode } from "./token-utils";

type TypeScaleTableProps = {
	source: TokenNode;
	sample?: string;
};

type TypographyEntry = {
	key: string;
	className: string;
	composite: Record<string, unknown>;
};

/**
 * Reads typography composite tokens (e.g. "24 med") off the top level of the
 * primitive token tree and renders each one as a live sample using the
 * matching `.text-<size>-<weight>` class generated by @pxds/cx-tokens.
 */
export function TypeScaleTable({
	source,
	sample = "가입자 정보를 확인해 주세요. The quick brown fox.",
}: TypeScaleTableProps): ReactElement {
	const entries: TypographyEntry[] = [];
	for (const [key, value] of Object.entries(source)) {
		const node = value as TokenNode | undefined;
		if (!node || typeof node !== "object") continue;
		if (node.$type !== "typography") continue;
		const slug = key.trim().replace(/\s+/g, "-").toLowerCase();
		entries.push({
			key,
			className: `text-${slug}`,
			composite: (node.$value as Record<string, unknown>) ?? {},
		});
	}

	const sortKey = (entry: TypographyEntry) => {
		const sizeMatch = entry.key.match(/(\d+)/);
		return sizeMatch ? Number(sizeMatch[1]) : 0;
	};
	entries.sort((a, b) => sortKey(b) - sortKey(a));

	return (
		<section style={{ marginBottom: 32 }}>
			<table
				style={{
					width: "100%",
					borderCollapse: "collapse",
					fontSize: 13,
				}}
			>
				<thead>
					<tr style={{ textAlign: "left" }}>
						<th style={th}>Token</th>
						<th style={th}>Class</th>
						<th style={th}>Sample</th>
					</tr>
				</thead>
				<tbody>
					{entries.map((entry) => (
						<tr key={entry.key}>
							<td style={td}>
								<code style={mono}>{entry.key}</code>
							</td>
							<td style={td}>
								<code style={mono}>.{entry.className}</code>
							</td>
							<td style={td}>
								<span className={entry.className}>{sample}</span>
							</td>
						</tr>
					))}
				</tbody>
			</table>
		</section>
	);
}

const th: React.CSSProperties = {
	padding: "8px",
	borderBottom: "1px solid var(--component-divider-default, #e5e5e5)",
	fontWeight: 600,
};

const td: React.CSSProperties = {
	padding: "8px",
	borderBottom: "1px solid var(--component-divider-default, #f1f1f1)",
	verticalAlign: "middle",
};

const mono: React.CSSProperties = {
	fontFamily: "ui-monospace, monospace",
	fontSize: 12,
	background: "rgba(0,0,0,0.04)",
	padding: "2px 6px",
	borderRadius: 4,
};
