export {
	benchmarkGlobalGuards,
	benchmarkCriteria,
	designBenchmarkCriteria,
	planningBenchmarkCriteria,
	type BenchmarkCriterion,
	type BenchmarkCriterionId,
	type BenchmarkScore,
	type BenchmarkSide,
} from "./benchmark";
export {
	createScreenAuditTable,
	formatScreenAuditTableMarkdown,
	type AuditJudgement,
	type ScreenAuditRow,
	type ScreenAuditSummary,
	type ScreenAuditTable,
} from "./audit";
export {
	activeRenderableScreenSpecs,
	activeScreenSpecs,
	type ActiveRenderableScreenSpecId,
	type ActiveScreenSpecId,
} from "./active-spec-list";
export {
	getScreenSpecIssues,
	type DesignException,
	type DesignSystemContract,
	type ScreenAreaContract,
	type ScreenLayoutContract,
	type ScreenSlotContract,
	type ScreenSpecIssue,
	type ScreenSpecIssueSeverity,
	type ScreenSpecV2,
	getRenderableScreenSpecIssues,
	type PolicyExtract,
	type RenderableScreenSpecV1,
	type ScreenBenchmarkTrace,
	type SDUIJsonValue,
	type SDUINode,
} from "./spec";

export type ScreenGroup =
	| "home"
	| "membership"
	| "product"
	| "search"
	| "tu"
	| "nc-full"
	| "nc-simple"
	| "billing"
	| "billing-html";

export type ScreenEntry = {
	id: string;
	path: `/${string}`;
	label: string;
	group: ScreenGroup;
	spec:
		| `spec/active/${string}.json`
		| `spec/inactive/${string}.json`
		| `spec/experimental/${string}.json`;
	renderSpec?:
		| `spec/active/${string}.sdui.json`
		| `spec/inactive/${string}.sdui.json`
		| `spec/experimental/${string}.sdui.json`;
	createdAt: `${number}-${number}-${number}`;
};

export const screens = [
	{
		id: "home-benefit",
		path: "/home-benefit",
		label: "홈 혜택",
		group: "home",
		spec: "spec/inactive/home-benefit.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-manage",
		path: "/home-manage",
		label: "관리 홈",
		group: "home",
		spec: "spec/inactive/home-manage.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-device-change",
		path: "/home-device-change",
		label: "기기 변경",
		group: "home",
		spec: "spec/inactive/home-device-change.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-senior",
		path: "/home-senior",
		label: "시니어 홈",
		group: "home",
		spec: "spec/inactive/home-senior.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-guest",
		path: "/home-guest",
		label: "게스트 홈",
		group: "home",
		spec: "spec/inactive/home-guest.json",
		createdAt: "2026-04-30",
	},
	{
		id: "product-detail",
		path: "/product-detail",
		label: "상품 상세",
		group: "product",
		spec: "spec/inactive/product-detail.json",
		renderSpec: "spec/inactive/product-detail.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-terms-consent",
		path: "/membership-terms-consent",
		label: "약관 동의",
		group: "membership",
		spec: "spec/active/membership/membership-terms-consent.json",
		renderSpec: "spec/active/membership/membership-terms-consent.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-join-complete",
		path: "/membership-join-complete",
		label: "가입 완료",
		group: "membership",
		spec: "spec/active/membership/membership-join-complete.json",
		renderSpec: "spec/active/membership/membership-join-complete.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-reason",
		path: "/membership-leave-reason",
		label: "탈퇴 사유",
		group: "membership",
		spec: "spec/active/membership/membership-leave-reason.json",
		renderSpec: "spec/active/membership/membership-leave-reason.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-personal-info",
		path: "/membership-personal-info",
		label: "개인정보 입력",
		group: "membership",
		spec: "spec/active/membership/membership-personal-info.json",
		renderSpec: "spec/active/membership/membership-personal-info.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-identity-verification",
		path: "/membership-identity-verification",
		label: "본인인증",
		group: "membership",
		spec: "spec/active/membership/membership-identity-verification.json",
		renderSpec: "spec/active/membership/membership-identity-verification.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-impact",
		path: "/membership-leave-impact",
		label: "탈퇴 영향",
		group: "membership",
		spec: "spec/active/membership/membership-leave-impact.json",
		renderSpec: "spec/active/membership/membership-leave-impact.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-complete",
		path: "/membership-leave-complete",
		label: "탈퇴 결과",
		group: "membership",
		spec: "spec/active/membership/membership-leave-complete.json",
		renderSpec: "spec/active/membership/membership-leave-complete.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "nc-full-join-terms",
		path: "/nc-full-join-terms",
		label: "NC 가입 1·약관 동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-terms.json",
		renderSpec: "spec/active/nc-full/nc-full-join-terms.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-info",
		path: "/nc-full-join-info",
		label: "NC 가입 2·개인정보 입력",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-info.json",
		renderSpec: "spec/active/nc-full/nc-full-join-info.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-auth",
		path: "/nc-full-join-auth",
		label: "NC 가입 3·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-join-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-complete",
		path: "/nc-full-join-complete",
		label: "NC 가입 4·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-complete.json",
		renderSpec: "spec/active/nc-full/nc-full-join-complete.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-auth",
		path: "/nc-full-leave-auth",
		label: "NC 탈퇴 1·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-reason",
		path: "/nc-full-leave-reason",
		label: "NC 탈퇴 2·사유",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-reason.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-reason.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-notice",
		path: "/nc-full-leave-notice",
		label: "NC 탈퇴 3·안내",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-notice.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-notice.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-confirm",
		path: "/nc-full-leave-confirm",
		label: "NC 탈퇴 4·최종 동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-confirm.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-confirm.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-result",
		path: "/nc-full-leave-result",
		label: "NC 탈퇴 5·결과",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-result.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-result.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-auth",
		path: "/nc-full-rejoin-auth",
		label: "NC 재가입 1·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-info",
		path: "/nc-full-rejoin-info",
		label: "NC 재가입 2·정보 입력",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-info.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-info.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-complete",
		path: "/nc-full-rejoin-complete",
		label: "NC 재가입 3·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-complete.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-complete.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-login",
		path: "/nc-full-dormancy-login",
		label: "NC 휴면 해제 1·로그인",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-login.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-login.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-auth",
		path: "/nc-full-dormancy-auth",
		label: "NC 휴면 해제 2·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-terms",
		path: "/nc-full-dormancy-terms",
		label: "NC 휴면 해제 3·약관 재동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-terms.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-terms.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-result",
		path: "/nc-full-dormancy-result",
		label: "NC 휴면 해제 4·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-result.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-result.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-simple-join-terms",
		path: "/nc-simple-join-terms",
		label: "NC-S 가입 1·약관 동의",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-terms.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-terms.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-info",
		path: "/nc-simple-join-info",
		label: "NC-S 가입 2·정보 입력",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-info.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-info.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-auth",
		path: "/nc-simple-join-auth",
		label: "NC-S 가입 3·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-complete",
		path: "/nc-simple-join-complete",
		label: "NC-S 가입 4·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-complete.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-complete.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-auth",
		path: "/nc-simple-leave-auth",
		label: "NC-S 탈퇴 1·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-reason",
		path: "/nc-simple-leave-reason",
		label: "NC-S 탈퇴 2·사유",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-reason.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-reason.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-confirm",
		path: "/nc-simple-leave-confirm",
		label: "NC-S 탈퇴 3·최종 확인",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-confirm.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-confirm.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-result",
		path: "/nc-simple-leave-result",
		label: "NC-S 탈퇴 4·결과",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-result.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-auth",
		path: "/nc-simple-rejoin-auth",
		label: "NC-S 재가입 1·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-info",
		path: "/nc-simple-rejoin-info",
		label: "NC-S 재가입 2·정보 입력",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-info.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-info.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-complete",
		path: "/nc-simple-rejoin-complete",
		label: "NC-S 재가입 3·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-complete.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-complete.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-blocked",
		path: "/nc-simple-rejoin-blocked",
		label: "NC-S 재가입·제한 안내",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-blocked.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-blocked.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-login",
		path: "/nc-simple-dormancy-login",
		label: "NC-S 휴면 해제 1·로그인",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-login.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-login.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-auth",
		path: "/nc-simple-dormancy-auth",
		label: "NC-S 휴면 해제 2·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-terms",
		path: "/nc-simple-dormancy-terms",
		label: "NC-S 휴면 해제 3·약관 재동의",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-terms.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-terms.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-result",
		path: "/nc-simple-dormancy-result",
		label: "NC-S 휴면 해제 4·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-result.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "search-result",
		path: "/search-result",
		label: "검색 결과",
		group: "search",
		spec: "spec/inactive/search-result.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-001-2",
		path: "/tu-dsp-main-mo-02-pg-001-2",
		label: "TU 발견",
		group: "tu",
		spec: "spec/inactive/tu-dsp-main-mo-02-pg-001-2.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-002",
		path: "/tu-dsp-main-mo-02-pg-002",
		label: "TU 권한",
		group: "tu",
		spec: "spec/inactive/tu-dsp-main-mo-02-pg-002.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-my-agr-mo-02-bs-001",
		path: "/tu-my-agr-mo-02-bs-001",
		label: "TU 바텀시트",
		group: "tu",
		spec: "spec/inactive/tu-my-agr-mo-02-bs-001.json",
		createdAt: "2026-04-30",
	},
	{
		id: "billing-summary",
		path: "/billing-summary",
		label: "청구 요약",
		group: "billing",
		spec: "spec/active/billing/billing-summary.json",
		renderSpec: "spec/active/billing/billing-summary.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-detail",
		path: "/billing-detail",
		label: "청구 상세 및 변동 사유",
		group: "billing",
		spec: "spec/active/billing/billing-detail.json",
		renderSpec: "spec/active/billing/billing-detail.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-realtime",
		path: "/billing-realtime",
		label: "실시간·예상 이용요금",
		group: "billing",
		spec: "spec/active/billing/billing-realtime.json",
		renderSpec: "spec/active/billing/billing-realtime.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-msc-history",
		path: "/billing-msc-history",
		label: "휴대폰결제·콘텐츠 이용내역",
		group: "billing",
		spec: "spec/active/billing/billing-msc-history.json",
		renderSpec: "spec/active/billing/billing-msc-history.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-statement",
		path: "/billing-statement",
		label: "요금안내서 조회",
		group: "billing",
		spec: "spec/active/billing/billing-statement.json",
		renderSpec: "spec/active/billing/billing-statement.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-statement-result",
		path: "/billing-statement-result",
		label: "요금안내서 재발행 결과",
		group: "billing",
		spec: "spec/active/billing/billing-statement-result.json",
		renderSpec: "spec/active/billing/billing-statement-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-target-select",
		path: "/billing-target-select",
		label: "납부 대상 선택",
		group: "billing",
		spec: "spec/active/billing/billing-target-select.json",
		renderSpec: "spec/active/billing/billing-target-select.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-payment-history",
		path: "/billing-payment-history",
		label: "납부 이력 및 증빙",
		group: "billing",
		spec: "spec/active/billing/billing-payment-history.json",
		renderSpec: "spec/active/billing/billing-payment-history.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-receipt-result",
		path: "/billing-receipt-result",
		label: "증빙 재발행 결과",
		group: "billing",
		spec: "spec/active/billing/billing-receipt-result.json",
		renderSpec: "spec/active/billing/billing-receipt-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-arrears-status",
		path: "/billing-arrears-status",
		label: "미납 해소·후속 상태",
		group: "billing",
		spec: "spec/active/billing/billing-arrears-status.json",
		renderSpec: "spec/active/billing/billing-arrears-status.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-method",
		path: "/billing-pay-method",
		label: "납부수단 선택",
		group: "billing",
		spec: "spec/active/billing/billing-pay-method.json",
		renderSpec: "spec/active/billing/billing-pay-method.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-method-auth",
		path: "/billing-pay-method-auth",
		label: "납부수단 인증·동의",
		group: "billing",
		spec: "spec/active/billing/billing-pay-method-auth.json",
		renderSpec: "spec/active/billing/billing-pay-method-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-confirm",
		path: "/billing-pay-confirm",
		label: "즉시 납부 확인",
		group: "billing",
		spec: "spec/active/billing/billing-pay-confirm.json",
		renderSpec: "spec/active/billing/billing-pay-confirm.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-result",
		path: "/billing-pay-result",
		label: "납부 결과",
		group: "billing",
		spec: "spec/active/billing/billing-pay-result.json",
		renderSpec: "spec/active/billing/billing-pay-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-schedule",
		path: "/billing-pay-schedule",
		label: "납부 예약·선납",
		group: "billing",
		spec: "spec/active/billing/billing-pay-schedule.json",
		renderSpec: "spec/active/billing/billing-pay-schedule.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-schedule-result",
		path: "/billing-pay-schedule-result",
		label: "예약 결과",
		group: "billing",
		spec: "spec/active/billing/billing-pay-schedule-result.json",
		renderSpec: "spec/active/billing/billing-pay-schedule-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy",
		path: "/billing-pay-proxy",
		label: "대리 납부 권한 확인",
		group: "billing",
		spec: "spec/active/billing/billing-pay-proxy.json",
		renderSpec: "spec/active/billing/billing-pay-proxy.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy-execute",
		path: "/billing-pay-proxy-execute",
		label: "대리 납부 실행",
		group: "billing",
		spec: "spec/active/billing/billing-pay-proxy-execute.json",
		renderSpec: "spec/active/billing/billing-pay-proxy-execute.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy-result",
		path: "/billing-pay-proxy-result",
		label: "대리 납부 결과",
		group: "billing",
		spec: "spec/active/billing/billing-pay-proxy-result.json",
		renderSpec: "spec/active/billing/billing-pay-proxy-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-third-party-consent",
		path: "/billing-pay-third-party-consent",
		label: "타인 명의 납부수단 동의",
		group: "billing",
		spec: "spec/active/billing/billing-pay-third-party-consent.json",
		renderSpec: "spec/active/billing/billing-pay-third-party-consent.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-prepay",
		path: "/billing-pay-prepay",
		label: "선결제",
		group: "billing",
		spec: "spec/active/billing/billing-pay-prepay.json",
		renderSpec: "spec/active/billing/billing-pay-prepay.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-prepay-result",
		path: "/billing-pay-prepay-result",
		label: "선결제 결과",
		group: "billing",
		spec: "spec/active/billing/billing-pay-prepay-result.json",
		renderSpec: "spec/active/billing/billing-pay-prepay-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-failure",
		path: "/billing-pay-failure",
		label: "납부 실패·후속",
		group: "billing",
		spec: "spec/active/billing/billing-pay-failure.json",
		renderSpec: "spec/active/billing/billing-pay-failure.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-statement",
		path: "/billing-set-statement",
		label: "요금안내서 수신 설정",
		group: "billing",
		spec: "spec/active/billing/billing-set-statement.json",
		renderSpec: "spec/active/billing/billing-set-statement.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method",
		path: "/billing-set-method",
		label: "납부방법 신청·변경",
		group: "billing",
		spec: "spec/active/billing/billing-set-method.json",
		renderSpec: "spec/active/billing/billing-set-method.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method-cancel",
		path: "/billing-set-method-cancel",
		label: "납부방법 해지",
		group: "billing",
		spec: "spec/active/billing/billing-set-method-cancel.json",
		renderSpec: "spec/active/billing/billing-set-method-cancel.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method-cancel-result",
		path: "/billing-set-method-cancel-result",
		label: "납부방법 해지 결과",
		group: "billing",
		spec: "spec/active/billing/billing-set-method-cancel-result.json",
		renderSpec: "spec/active/billing/billing-set-method-cancel-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-msc-limit",
		path: "/billing-set-msc-limit",
		label: "휴대폰 결제 이용한도",
		group: "billing",
		spec: "spec/active/billing/billing-set-msc-limit.json",
		renderSpec: "spec/active/billing/billing-set-msc-limit.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-content-limit",
		path: "/billing-set-content-limit",
		label: "콘텐츠 이용료 한도",
		group: "billing",
		spec: "spec/active/billing/billing-set-content-limit.json",
		renderSpec: "spec/active/billing/billing-set-content-limit.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-auto-prepay",
		path: "/billing-set-auto-prepay",
		label: "자동 선결제 설정",
		group: "billing",
		spec: "spec/active/billing/billing-set-auto-prepay.json",
		renderSpec: "spec/active/billing/billing-set-auto-prepay.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-arrears-status",
		path: "/billing-html-arrears-status",
		label: "[HTML] 미납 해소 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-arrears-status.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-arrears-status.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-detail",
		path: "/billing-html-detail",
		label: "[HTML] 청구 상세 및 변동 사유",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-detail.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-detail.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-msc-history",
		path: "/billing-html-msc-history",
		label: "[HTML] 휴대폰결제·콘텐츠 이용내역",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-msc-history.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-msc-history.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-confirm",
		path: "/billing-html-pay-confirm",
		label: "[HTML] 즉시 납부 확인",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-confirm.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-confirm.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-failure",
		path: "/billing-html-pay-failure",
		label: "[HTML] 납부 실패 후속",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-failure.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-failure.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-method-auth",
		path: "/billing-html-pay-method-auth",
		label: "[HTML] 납부수단 인증",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-method-auth.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-method-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-method",
		path: "/billing-html-pay-method",
		label: "[HTML] 납부수단 선택",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-method.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-method.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-prepay-result",
		path: "/billing-html-pay-prepay-result",
		label: "[HTML] 선결제 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-prepay-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-prepay-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-prepay",
		path: "/billing-html-pay-prepay",
		label: "[HTML] 선결제",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-prepay.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-prepay.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy-execute",
		path: "/billing-html-pay-proxy-execute",
		label: "[HTML] 대리 납부 실행",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-proxy-execute.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-proxy-execute.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy-result",
		path: "/billing-html-pay-proxy-result",
		label: "[HTML] 대리 납부 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-proxy-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-proxy-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy",
		path: "/billing-html-pay-proxy",
		label: "[HTML] 대리 납부",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-proxy.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-proxy.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-result",
		path: "/billing-html-pay-result",
		label: "[HTML] 납부 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-schedule-result",
		path: "/billing-html-pay-schedule-result",
		label: "[HTML] 납부 예약 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-schedule-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-schedule-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-schedule",
		path: "/billing-html-pay-schedule",
		label: "[HTML] 납부 예약",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-schedule.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-schedule.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-third-party-consent",
		path: "/billing-html-pay-third-party-consent",
		label: "[HTML] 타인 명의 동의",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-pay-third-party-consent.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-pay-third-party-consent.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-payment-history",
		path: "/billing-html-payment-history",
		label: "[HTML] 납부 이력",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-payment-history.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-payment-history.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-realtime",
		path: "/billing-html-realtime",
		label: "[HTML] 실시간·예상 이용요금",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-realtime.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-realtime.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-receipt-result",
		path: "/billing-html-receipt-result",
		label: "[HTML] 증빙 발급 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-receipt-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-receipt-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-auto-prepay",
		path: "/billing-html-set-auto-prepay",
		label: "[HTML] 자동 선결제 설정",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-auto-prepay.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-auto-prepay.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-content-limit",
		path: "/billing-html-set-content-limit",
		label: "[HTML] 콘텐츠 이용료 한도",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-content-limit.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-content-limit.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method-cancel-result",
		path: "/billing-html-set-method-cancel-result",
		label: "[HTML] 납부방법 해지 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-method-cancel-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-method-cancel-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method-cancel",
		path: "/billing-html-set-method-cancel",
		label: "[HTML] 납부방법 해지",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-method-cancel.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-method-cancel.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method",
		path: "/billing-html-set-method",
		label: "[HTML] 납부방법 신청·변경",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-method.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-method.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-msc-limit",
		path: "/billing-html-set-msc-limit",
		label: "[HTML] 휴대폰 결제 한도",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-msc-limit.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-msc-limit.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-statement",
		path: "/billing-html-set-statement",
		label: "[HTML] 요금안내서 수신 설정",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-set-statement.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-set-statement.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-statement-result",
		path: "/billing-html-statement-result",
		label: "[HTML] 요금안내서 발급 결과",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-statement-result.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-statement-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-statement",
		path: "/billing-html-statement",
		label: "[HTML] 요금안내서 조회",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-statement.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-statement.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-summary",
		path: "/billing-html-summary",
		label: "[HTML] 청구 요약",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-summary.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-summary.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-target-select",
		path: "/billing-html-target-select",
		label: "[HTML] 납부 대상 선택",
		group: "billing-html",
		spec: "spec/experimental/billing-from-html/billing-html-target-select.json",
		renderSpec: "spec/experimental/billing-from-html/billing-html-target-select.sdui.json",
		createdAt: "2026-05-06",
	},
] as const satisfies readonly ScreenEntry[];

export type ScreenId = (typeof screens)[number]["id"];
export type ScreenPath = (typeof screens)[number]["path"];

export const screenCount = screens.length;
