export {
	benchmarkGlobalGuards,
	benchmarkCriteria,
	designBenchmarkCriteria,
	planningBenchmarkCriteria,
	type BenchmarkCriterion,
	type BenchmarkCriterionId,
	type BenchmarkScore,
	type BenchmarkSide,
} from "./benchmark";
export {
	activeRenderableScreenSpecs,
	activeScreenSpecs,
	type ActiveRenderableScreenSpecId,
	type ActiveScreenSpecId,
} from "./active-spec-list";
export {
	getScreenSpecIssues,
	type DesignException,
	type DesignSystemContract,
	type ScreenAreaContract,
	type ScreenLayoutContract,
	type ScreenSlotContract,
	type ScreenSpecIssue,
	type ScreenSpecIssueSeverity,
	type ScreenSpecV2,
	getRenderableScreenSpecIssues,
	type PolicyExtract,
	type RenderableScreenSpecV1,
	type ScreenBenchmarkTrace,
	type SDUIJsonValue,
	type SDUINode,
} from "./spec";

export type ScreenGroup =
	| "home"
	| "membership"
	| "product"
	| "search"
	| "tu"
	| "nc-full"
	| "nc-simple";

export type ScreenEntry = {
	id: string;
	path: `/${string}`;
	label: string;
	group: ScreenGroup;
	spec: `spec/active/${string}.json` | `spec/inactive/${string}.json`;
	renderSpec?:
		| `spec/active/${string}.sdui.json`
		| `spec/inactive/${string}.sdui.json`;
	createdAt: `${number}-${number}-${number}`;
};

export const screens = [
	{
		id: "home-benefit",
		path: "/home-benefit",
		label: "홈 혜택",
		group: "home",
		spec: "spec/inactive/home-benefit.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-manage",
		path: "/home-manage",
		label: "관리 홈",
		group: "home",
		spec: "spec/inactive/home-manage.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-device-change",
		path: "/home-device-change",
		label: "기기 변경",
		group: "home",
		spec: "spec/inactive/home-device-change.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-senior",
		path: "/home-senior",
		label: "시니어 홈",
		group: "home",
		spec: "spec/inactive/home-senior.json",
		createdAt: "2026-04-30",
	},
	{
		id: "home-guest",
		path: "/home-guest",
		label: "게스트 홈",
		group: "home",
		spec: "spec/inactive/home-guest.json",
		createdAt: "2026-04-30",
	},
	{
		id: "product-detail",
		path: "/product-detail",
		label: "상품 상세",
		group: "product",
		spec: "spec/inactive/product-detail.json",
		renderSpec: "spec/inactive/product-detail.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-terms-consent",
		path: "/membership-terms-consent",
		label: "약관 동의",
		group: "membership",
		spec: "spec/active/membership/membership-terms-consent.json",
		renderSpec: "spec/active/membership/membership-terms-consent.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-join-complete",
		path: "/membership-join-complete",
		label: "가입 완료",
		group: "membership",
		spec: "spec/active/membership/membership-join-complete.json",
		renderSpec: "spec/active/membership/membership-join-complete.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-reason",
		path: "/membership-leave-reason",
		label: "탈퇴 사유",
		group: "membership",
		spec: "spec/active/membership/membership-leave-reason.json",
		renderSpec: "spec/active/membership/membership-leave-reason.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-personal-info",
		path: "/membership-personal-info",
		label: "개인정보 입력",
		group: "membership",
		spec: "spec/active/membership/membership-personal-info.json",
		renderSpec: "spec/active/membership/membership-personal-info.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-identity-verification",
		path: "/membership-identity-verification",
		label: "본인인증",
		group: "membership",
		spec: "spec/active/membership/membership-identity-verification.json",
		renderSpec: "spec/active/membership/membership-identity-verification.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-impact",
		path: "/membership-leave-impact",
		label: "탈퇴 영향",
		group: "membership",
		spec: "spec/active/membership/membership-leave-impact.json",
		renderSpec: "spec/active/membership/membership-leave-impact.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-complete",
		path: "/membership-leave-complete",
		label: "탈퇴 결과",
		group: "membership",
		spec: "spec/active/membership/membership-leave-complete.json",
		renderSpec: "spec/active/membership/membership-leave-complete.sdui.json",
		createdAt: "2026-04-30",
	},
	{
		id: "nc-full-join-terms",
		path: "/nc-full-join-terms",
		label: "NC 가입 1·약관 동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-terms.json",
		renderSpec: "spec/active/nc-full/nc-full-join-terms.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-info",
		path: "/nc-full-join-info",
		label: "NC 가입 2·개인정보 입력",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-info.json",
		renderSpec: "spec/active/nc-full/nc-full-join-info.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-auth",
		path: "/nc-full-join-auth",
		label: "NC 가입 3·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-join-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-complete",
		path: "/nc-full-join-complete",
		label: "NC 가입 4·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-join-complete.json",
		renderSpec: "spec/active/nc-full/nc-full-join-complete.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-auth",
		path: "/nc-full-leave-auth",
		label: "NC 탈퇴 1·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-reason",
		path: "/nc-full-leave-reason",
		label: "NC 탈퇴 2·사유",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-reason.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-reason.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-notice",
		path: "/nc-full-leave-notice",
		label: "NC 탈퇴 3·안내",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-notice.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-notice.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-confirm",
		path: "/nc-full-leave-confirm",
		label: "NC 탈퇴 4·최종 동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-confirm.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-confirm.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-result",
		path: "/nc-full-leave-result",
		label: "NC 탈퇴 5·결과",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-leave-result.json",
		renderSpec: "spec/active/nc-full/nc-full-leave-result.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-auth",
		path: "/nc-full-rejoin-auth",
		label: "NC 재가입 1·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-info",
		path: "/nc-full-rejoin-info",
		label: "NC 재가입 2·정보 입력",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-info.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-info.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-complete",
		path: "/nc-full-rejoin-complete",
		label: "NC 재가입 3·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-rejoin-complete.json",
		renderSpec: "spec/active/nc-full/nc-full-rejoin-complete.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-login",
		path: "/nc-full-dormancy-login",
		label: "NC 휴면 해제 1·로그인",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-login.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-login.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-auth",
		path: "/nc-full-dormancy-auth",
		label: "NC 휴면 해제 2·본인인증",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-auth.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-auth.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-terms",
		path: "/nc-full-dormancy-terms",
		label: "NC 휴면 해제 3·약관 재동의",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-terms.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-terms.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-result",
		path: "/nc-full-dormancy-result",
		label: "NC 휴면 해제 4·완료",
		group: "nc-full",
		spec: "spec/active/nc-full/nc-full-dormancy-result.json",
		renderSpec: "spec/active/nc-full/nc-full-dormancy-result.sdui.json",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-simple-join-terms",
		path: "/nc-simple-join-terms",
		label: "NC-S 가입 1·약관 동의",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-terms.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-terms.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-info",
		path: "/nc-simple-join-info",
		label: "NC-S 가입 2·정보 입력",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-info.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-info.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-auth",
		path: "/nc-simple-join-auth",
		label: "NC-S 가입 3·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-complete",
		path: "/nc-simple-join-complete",
		label: "NC-S 가입 4·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-join-complete.json",
		renderSpec: "spec/active/nc-simple/nc-simple-join-complete.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-auth",
		path: "/nc-simple-leave-auth",
		label: "NC-S 탈퇴 1·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-reason",
		path: "/nc-simple-leave-reason",
		label: "NC-S 탈퇴 2·사유",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-reason.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-reason.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-confirm",
		path: "/nc-simple-leave-confirm",
		label: "NC-S 탈퇴 3·최종 확인",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-confirm.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-confirm.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-result",
		path: "/nc-simple-leave-result",
		label: "NC-S 탈퇴 4·결과",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-leave-result.json",
		renderSpec: "spec/active/nc-simple/nc-simple-leave-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-auth",
		path: "/nc-simple-rejoin-auth",
		label: "NC-S 재가입 1·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-info",
		path: "/nc-simple-rejoin-info",
		label: "NC-S 재가입 2·정보 입력",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-info.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-info.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-complete",
		path: "/nc-simple-rejoin-complete",
		label: "NC-S 재가입 3·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-complete.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-complete.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-blocked",
		path: "/nc-simple-rejoin-blocked",
		label: "NC-S 재가입·제한 안내",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-rejoin-blocked.json",
		renderSpec: "spec/active/nc-simple/nc-simple-rejoin-blocked.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-login",
		path: "/nc-simple-dormancy-login",
		label: "NC-S 휴면 해제 1·로그인",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-login.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-login.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-auth",
		path: "/nc-simple-dormancy-auth",
		label: "NC-S 휴면 해제 2·본인인증",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-auth.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-auth.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-terms",
		path: "/nc-simple-dormancy-terms",
		label: "NC-S 휴면 해제 3·약관 재동의",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-terms.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-terms.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-result",
		path: "/nc-simple-dormancy-result",
		label: "NC-S 휴면 해제 4·완료",
		group: "nc-simple",
		spec: "spec/active/nc-simple/nc-simple-dormancy-result.json",
		renderSpec: "spec/active/nc-simple/nc-simple-dormancy-result.sdui.json",
		createdAt: "2026-05-06",
	},
	{
		id: "search-result",
		path: "/search-result",
		label: "검색 결과",
		group: "search",
		spec: "spec/inactive/search-result.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-001-2",
		path: "/tu-dsp-main-mo-02-pg-001-2",
		label: "TU 발견",
		group: "tu",
		spec: "spec/inactive/tu-dsp-main-mo-02-pg-001-2.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-002",
		path: "/tu-dsp-main-mo-02-pg-002",
		label: "TU 권한",
		group: "tu",
		spec: "spec/inactive/tu-dsp-main-mo-02-pg-002.json",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-my-agr-mo-02-bs-001",
		path: "/tu-my-agr-mo-02-bs-001",
		label: "TU 바텀시트",
		group: "tu",
		spec: "spec/inactive/tu-my-agr-mo-02-bs-001.json",
		createdAt: "2026-04-30",
	},
] as const satisfies readonly ScreenEntry[];

export type ScreenId = (typeof screens)[number]["id"];
export type ScreenPath = (typeof screens)[number]["path"];

export const screenCount = screens.length;
