export const formFieldFigmaSpec = {
	$schema: "component-spec-v1",
	name: "mol/form-field",
	category: "mol",
	description: "Label, helper, and field composition boundary.",
	widthFallback: "{dimension.size.screen-content-width}",
	base: {
		layout: {
			mode: "VERTICAL",
			primaryAxisSizingMode: "AUTO",
			counterAxisSizingMode: "AUTO",
			itemSpacing: "{spacing.8}",
			width: "FILL",
		},
		children: [
			{
				kind: "text",
				id: "label",
				content: "옵션",
				textStyle: "{typography.label1.medium}",
				color: "{color.semantic.label.normal}",
				exposeAs: "label",
			},
			{
				kind: "group",
				id: "field",
				layout: {
					mode: "HORIZONTAL",
					primaryAxisSizingMode: "FIXED",
					counterAxisSizingMode: "FIXED",
					counterAxisAlignItems: "CENTER",
					paddingLeft: "{spacing.16}",
					paddingRight: "{spacing.16}",
					itemSpacing: "{spacing.8}",
					width: "FILL",
					height: "48px",
				},
				visual: {
					fill: "{color.semantic.background.elevated.normal}",
					stroke: {
						color: "{color.semantic.line.normal.normal}",
						weight: 1,
					},
					cornerRadius: "{spacing.8}",
				},
				layoutAlign: "STRETCH",
				children: [
					{
						kind: "text",
						id: "value",
						content: "기본 옵션",
						textStyle: "{typography.body1.regular}",
						color: "{color.semantic.label.normal}",
						layoutGrow: 1,
						autoResize: "HEIGHT",
						exposeAs: "value",
					},
					{
						kind: "text",
						id: "indicator",
						content: "⌄",
						textStyle: "{typography.body1.medium}",
						color: "{color.semantic.label.assistive}",
					},
				],
			},
			{
				kind: "text",
				id: "helper",
				content: "선택 가능한 값을 확인합니다.",
				textStyle: "{typography.caption1.regular}",
				color: "{color.semantic.label.alternative}",
				exposeAs: "helperText",
			},
		],
	},
};
