export const wdsCoreRegistryEntries = [
	{
		id: "wds-typography",
		name: "Typography",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "typography",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-button",
		name: "Button",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-icon-button",
		name: "IconButton",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-text-button",
		name: "TextButton",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-checkbox",
		name: "Checkbox",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "form",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-radio-group-item",
		name: "RadioGroupItem",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "form",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-chip",
		name: "Chip",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "selection",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-content-badge",
		name: "ContentBadge",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "feedback",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-thumbnail",
		name: "Thumbnail",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "media",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-progress-indicator",
		name: "ProgressIndicator",
		layer: "atom",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "feedback",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-card",
		name: "Card",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "layout",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-card-content",
		name: "CardContent",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "layout",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-card-title",
		name: "CardTitle",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "typography",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-list",
		name: "List",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "layout",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-list-cell",
		name: "ListCell",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "layout",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-list-cell-content",
		name: "ListCellContent",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "layout",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-radio-group",
		name: "RadioGroup",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "form",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-section-message",
		name: "SectionMessage",
		layer: "molecule",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "feedback",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-top-navigation",
		name: "TopNavigation",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-top-navigation-button",
		name: "TopNavigationButton",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-bottom-navigation",
		name: "BottomNavigation",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-bottom-navigation-item",
		name: "BottomNavigationItem",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "navigation",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-modal",
		name: "Modal",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "template",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-modal-container",
		name: "ModalContainer",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "template",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-modal-content",
		name: "ModalContent",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "template",
		status: "active",
		createdAt: "2026-05-11",
	},
	{
		id: "wds-modal-dimmer",
		name: "ModalDimmer",
		layer: "organism",
		owner: "@pxds/pxds-components",
		importPath: "@pxds/pxds-components/core",
		group: "template",
		status: "active",
		createdAt: "2026-05-11",
	},
] as const;
