export type ScreenGroup =
	| "home"
	| "membership"
	| "product"
	| "search"
	| "tu"
	| "nc-full"
	| "nc-simple"
	| "billing"
	| "billing-html";

export type ScreenLifecycleStatus = "active" | "inactive" | "experimental";

/**
 * Route-level screen record.
 *
 * This is the preview/app routing source of truth. It intentionally does not
 * know where spec artifacts live; spec ownership belongs to @screen/specs.
 */
export type ScreenRoute = {
	id: string;
	route: `/${string}`;
	label: string;
	group: ScreenGroup;
	status: ScreenLifecycleStatus;
	createdAt: `${number}-${number}-${number}`;
};

export const screenRoutes = [
	{
		id: "home-benefit",
		route: "/home-benefit",
		label: "홈 혜택",
		group: "home",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "home-manage",
		route: "/home-manage",
		label: "관리 홈",
		group: "home",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "home-device-change",
		route: "/home-device-change",
		label: "기기 변경",
		group: "home",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "home-senior",
		route: "/home-senior",
		label: "시니어 홈",
		group: "home",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "home-guest",
		route: "/home-guest",
		label: "게스트 홈",
		group: "home",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "product-detail",
		route: "/product-detail",
		label: "상품 상세",
		group: "product",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-terms-consent",
		route: "/membership-terms-consent",
		label: "약관 동의",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-join-complete",
		route: "/membership-join-complete",
		label: "가입 완료",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-reason",
		route: "/membership-leave-reason",
		label: "탈퇴 사유",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-personal-info",
		route: "/membership-personal-info",
		label: "개인정보 입력",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-identity-verification",
		route: "/membership-identity-verification",
		label: "본인인증",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-impact",
		route: "/membership-leave-impact",
		label: "탈퇴 영향",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "membership-leave-complete",
		route: "/membership-leave-complete",
		label: "탈퇴 결과",
		group: "membership",
		status: "active",
		createdAt: "2026-04-30",
	},
	{
		id: "nc-full-join-terms",
		route: "/nc-full-join-terms",
		label: "NC 가입 1·약관 동의",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-info",
		route: "/nc-full-join-info",
		label: "NC 가입 2·개인정보 입력",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-auth",
		route: "/nc-full-join-auth",
		label: "NC 가입 3·본인인증",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-join-complete",
		route: "/nc-full-join-complete",
		label: "NC 가입 4·완료",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-auth",
		route: "/nc-full-leave-auth",
		label: "NC 탈퇴 1·본인인증",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-reason",
		route: "/nc-full-leave-reason",
		label: "NC 탈퇴 2·사유",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-notice",
		route: "/nc-full-leave-notice",
		label: "NC 탈퇴 3·안내",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-confirm",
		route: "/nc-full-leave-confirm",
		label: "NC 탈퇴 4·최종 동의",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-leave-result",
		route: "/nc-full-leave-result",
		label: "NC 탈퇴 5·결과",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-auth",
		route: "/nc-full-rejoin-auth",
		label: "NC 재가입 1·본인인증",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-info",
		route: "/nc-full-rejoin-info",
		label: "NC 재가입 2·정보 입력",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-rejoin-complete",
		route: "/nc-full-rejoin-complete",
		label: "NC 재가입 3·완료",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-login",
		route: "/nc-full-dormancy-login",
		label: "NC 휴면 해제 1·로그인",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-auth",
		route: "/nc-full-dormancy-auth",
		label: "NC 휴면 해제 2·본인인증",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-terms",
		route: "/nc-full-dormancy-terms",
		label: "NC 휴면 해제 3·약관 재동의",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-full-dormancy-result",
		route: "/nc-full-dormancy-result",
		label: "NC 휴면 해제 4·완료",
		group: "nc-full",
		status: "active",
		createdAt: "2026-05-04",
	},
	{
		id: "nc-simple-join-terms",
		route: "/nc-simple-join-terms",
		label: "NC-S 가입 1·약관 동의",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-info",
		route: "/nc-simple-join-info",
		label: "NC-S 가입 2·정보 입력",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-auth",
		route: "/nc-simple-join-auth",
		label: "NC-S 가입 3·본인인증",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-join-complete",
		route: "/nc-simple-join-complete",
		label: "NC-S 가입 4·완료",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-auth",
		route: "/nc-simple-leave-auth",
		label: "NC-S 탈퇴 1·본인인증",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-reason",
		route: "/nc-simple-leave-reason",
		label: "NC-S 탈퇴 2·사유",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-confirm",
		route: "/nc-simple-leave-confirm",
		label: "NC-S 탈퇴 3·최종 확인",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-leave-result",
		route: "/nc-simple-leave-result",
		label: "NC-S 탈퇴 4·결과",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-auth",
		route: "/nc-simple-rejoin-auth",
		label: "NC-S 재가입 1·본인인증",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-info",
		route: "/nc-simple-rejoin-info",
		label: "NC-S 재가입 2·정보 입력",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-complete",
		route: "/nc-simple-rejoin-complete",
		label: "NC-S 재가입 3·완료",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-rejoin-blocked",
		route: "/nc-simple-rejoin-blocked",
		label: "NC-S 재가입·제한 안내",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-login",
		route: "/nc-simple-dormancy-login",
		label: "NC-S 휴면 해제 1·로그인",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-auth",
		route: "/nc-simple-dormancy-auth",
		label: "NC-S 휴면 해제 2·본인인증",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-terms",
		route: "/nc-simple-dormancy-terms",
		label: "NC-S 휴면 해제 3·약관 재동의",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "nc-simple-dormancy-result",
		route: "/nc-simple-dormancy-result",
		label: "NC-S 휴면 해제 4·완료",
		group: "nc-simple",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "search-result",
		route: "/search-result",
		label: "검색 결과",
		group: "search",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-001-2",
		route: "/tu-dsp-main-mo-02-pg-001-2",
		label: "TU 발견",
		group: "tu",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-dsp-main-mo-02-pg-002",
		route: "/tu-dsp-main-mo-02-pg-002",
		label: "TU 권한",
		group: "tu",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "tu-my-agr-mo-02-bs-001",
		route: "/tu-my-agr-mo-02-bs-001",
		label: "TU 바텀시트",
		group: "tu",
		status: "inactive",
		createdAt: "2026-04-30",
	},
	{
		id: "billing-summary",
		route: "/billing-summary",
		label: "청구 요약",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-detail",
		route: "/billing-detail",
		label: "청구 상세 및 변동 사유",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-realtime",
		route: "/billing-realtime",
		label: "실시간·예상 이용요금",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-msc-history",
		route: "/billing-msc-history",
		label: "휴대폰결제·콘텐츠 이용내역",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-statement",
		route: "/billing-statement",
		label: "요금안내서 조회",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-statement-result",
		route: "/billing-statement-result",
		label: "요금안내서 재발행 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-target-select",
		route: "/billing-target-select",
		label: "납부 대상 선택",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-payment-history",
		route: "/billing-payment-history",
		label: "납부 이력 및 증빙",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-receipt-result",
		route: "/billing-receipt-result",
		label: "증빙 재발행 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-arrears-status",
		route: "/billing-arrears-status",
		label: "미납 해소·후속 상태",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-method",
		route: "/billing-pay-method",
		label: "납부수단 선택",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-method-auth",
		route: "/billing-pay-method-auth",
		label: "납부수단 인증·동의",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-confirm",
		route: "/billing-pay-confirm",
		label: "즉시 납부 확인",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-result",
		route: "/billing-pay-result",
		label: "납부 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-schedule",
		route: "/billing-pay-schedule",
		label: "납부 예약·선납",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-schedule-result",
		route: "/billing-pay-schedule-result",
		label: "예약 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy",
		route: "/billing-pay-proxy",
		label: "대리 납부 권한 확인",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy-execute",
		route: "/billing-pay-proxy-execute",
		label: "대리 납부 실행",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-proxy-result",
		route: "/billing-pay-proxy-result",
		label: "대리 납부 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-third-party-consent",
		route: "/billing-pay-third-party-consent",
		label: "타인 명의 납부수단 동의",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-prepay",
		route: "/billing-pay-prepay",
		label: "선결제",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-prepay-result",
		route: "/billing-pay-prepay-result",
		label: "선결제 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-pay-failure",
		route: "/billing-pay-failure",
		label: "납부 실패·후속",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-statement",
		route: "/billing-set-statement",
		label: "요금안내서 수신 설정",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method",
		route: "/billing-set-method",
		label: "납부방법 신청·변경",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method-cancel",
		route: "/billing-set-method-cancel",
		label: "납부방법 해지",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-method-cancel-result",
		route: "/billing-set-method-cancel-result",
		label: "납부방법 해지 결과",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-msc-limit",
		route: "/billing-set-msc-limit",
		label: "휴대폰 결제 이용한도",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-content-limit",
		route: "/billing-set-content-limit",
		label: "콘텐츠 이용료 한도",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-set-auto-prepay",
		route: "/billing-set-auto-prepay",
		label: "자동 선결제 설정",
		group: "billing",
		status: "active",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-arrears-status",
		route: "/billing-html-arrears-status",
		label: "[HTML] 미납 해소 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-detail",
		route: "/billing-html-detail",
		label: "[HTML] 청구 상세 및 변동 사유",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-msc-history",
		route: "/billing-html-msc-history",
		label: "[HTML] 휴대폰결제·콘텐츠 이용내역",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-confirm",
		route: "/billing-html-pay-confirm",
		label: "[HTML] 즉시 납부 확인",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-failure",
		route: "/billing-html-pay-failure",
		label: "[HTML] 납부 실패 후속",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-method-auth",
		route: "/billing-html-pay-method-auth",
		label: "[HTML] 납부수단 인증",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-method",
		route: "/billing-html-pay-method",
		label: "[HTML] 납부수단 선택",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-prepay-result",
		route: "/billing-html-pay-prepay-result",
		label: "[HTML] 선결제 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-prepay",
		route: "/billing-html-pay-prepay",
		label: "[HTML] 선결제",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy-execute",
		route: "/billing-html-pay-proxy-execute",
		label: "[HTML] 대리 납부 실행",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy-result",
		route: "/billing-html-pay-proxy-result",
		label: "[HTML] 대리 납부 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-proxy",
		route: "/billing-html-pay-proxy",
		label: "[HTML] 대리 납부",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-result",
		route: "/billing-html-pay-result",
		label: "[HTML] 납부 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-schedule-result",
		route: "/billing-html-pay-schedule-result",
		label: "[HTML] 납부 예약 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-schedule",
		route: "/billing-html-pay-schedule",
		label: "[HTML] 납부 예약",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-pay-third-party-consent",
		route: "/billing-html-pay-third-party-consent",
		label: "[HTML] 타인 명의 동의",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-payment-history",
		route: "/billing-html-payment-history",
		label: "[HTML] 납부 이력",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-realtime",
		route: "/billing-html-realtime",
		label: "[HTML] 실시간·예상 이용요금",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-receipt-result",
		route: "/billing-html-receipt-result",
		label: "[HTML] 증빙 발급 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-auto-prepay",
		route: "/billing-html-set-auto-prepay",
		label: "[HTML] 자동 선결제 설정",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-content-limit",
		route: "/billing-html-set-content-limit",
		label: "[HTML] 콘텐츠 이용료 한도",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method-cancel-result",
		route: "/billing-html-set-method-cancel-result",
		label: "[HTML] 납부방법 해지 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method-cancel",
		route: "/billing-html-set-method-cancel",
		label: "[HTML] 납부방법 해지",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-method",
		route: "/billing-html-set-method",
		label: "[HTML] 납부방법 신청·변경",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-msc-limit",
		route: "/billing-html-set-msc-limit",
		label: "[HTML] 휴대폰 결제 한도",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-set-statement",
		route: "/billing-html-set-statement",
		label: "[HTML] 요금안내서 수신 설정",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-statement-result",
		route: "/billing-html-statement-result",
		label: "[HTML] 요금안내서 발급 결과",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-statement",
		route: "/billing-html-statement",
		label: "[HTML] 요금안내서 조회",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-summary",
		route: "/billing-html-summary",
		label: "[HTML] 청구 요약",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	},
	{
		id: "billing-html-target-select",
		route: "/billing-html-target-select",
		label: "[HTML] 납부 대상 선택",
		group: "billing-html",
		status: "experimental",
		createdAt: "2026-05-06",
	}
] as const satisfies readonly ScreenRoute[];

export type ScreenId = (typeof screenRoutes)[number]["id"];
export type ScreenRoutePath = (typeof screenRoutes)[number]["route"];

export const screenCount = screenRoutes.length;
