export {
	addHexOpacity,
	darkOriginTheme,
	darkTheme,
	getColorByToken,
	lightOriginTheme,
	lightTheme,
	theme,
	type BreakPoint,
	type Spacing,
	type Theme,
	type ThemeColorsToken,
	type ThemeOpacityToken,
	type ThemeShadowToken,
	type ThemeToken,
} from "@wanteddev/wds-theme";
