import type { CxComponentPreviewEntry } from "./types";

export const cxComponentPreviewRegistry = [
	{
		id: "status-bar",
		name: "StatusBar",
		layer: "base",
		group: "navigation",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/status-bar",
		status: "active",
	},
	{
		id: "app-bar",
		name: "AppBar",
		layer: "base",
		group: "navigation",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/app-bar",
		status: "active",
	},
	{
		id: "title-main",
		name: "TitleMain",
		layer: "base",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/title-main",
		status: "active",
	},
	{
		id: "title-section",
		name: "TitleSection",
		layer: "base",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/title-section",
		status: "active",
	},
	{
		id: "text",
		name: "Text",
		layer: "base",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/text",
		status: "active",
	},
	{
		id: "text-field",
		name: "TextField",
		layer: "base",
		group: "form",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/text-field",
		status: "active",
	},
	{
		id: "button",
		name: "Button",
		layer: "base",
		group: "action",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/button",
		status: "active",
	},
	{
		id: "action-button",
		name: "ActionButton",
		layer: "base",
		group: "action",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/action-button",
		status: "active",
	},
	{
		id: "checkbox",
		name: "Checkbox",
		layer: "base",
		group: "selection",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/checkbox",
		status: "active",
	},
	{
		id: "chips",
		name: "Chips",
		layer: "base",
		group: "selection",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/chips",
		status: "active",
	},
	{
		id: "list-text",
		name: "ListText",
		layer: "base",
		group: "layout",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/list-text",
		status: "active",
	},
	{
		id: "section-item",
		name: "SectionItem",
		layer: "base",
		group: "layout",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/section-item",
		status: "active",
	},
	{
		id: "callout",
		name: "Callout",
		layer: "base",
		group: "feedback",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/callout",
		status: "active",
	},
	{
		id: "search-bar",
		name: "SearchBar",
		layer: "base",
		group: "form",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/search-bar",
		status: "active",
	},
	{
		id: "divider",
		name: "Divider",
		layer: "base",
		group: "feedback",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/divider",
		status: "active",
	},
	{
		id: "rqr-list-option",
		name: "RQRListOption",
		layer: "base",
		group: "form",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/candidate/rqr-list-option",
		status: "candidate",
		candidateKind: "new",
	},
	{
		id: "rqr-notice",
		name: "RQRNotice",
		layer: "base",
		group: "feedback",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/candidate/rqr-notice",
		status: "candidate",
		candidateKind: "new",
	},
] as const satisfies readonly CxComponentPreviewEntry[];
