export const screenMap = {
	screenId: "NOVA-MBR-FP-003-0-CX",
	sourceScreenId: "NOVA-MBR-FP-003-0",
	screenName: "본인인증",
	domain: "MBR",
	useCaseId: "MBR-UC01",
	flowContext: "회원 가입 플로우, 개인정보 입력 이후 가입자의 본인 여부를 확인한다.",
	verificationLevel: "policy-backed-green",
	coverage: [
		{
			target: "NOVA-MBR-FP-003-0-CX",
			referencedPolicyIds: [
				"POL-MBR-AUTH-001-01",
				"POL-MBR-AUTH-002-01",
				"POL-MBR-AUTH-002-05",
				"POL-MBR-AUTH-002-09",
				"POL-MBR-AUTH-003-01",
				"POL-MBR-AUTH-003-03",
				"POL-MBR-AUTH-004-01",
				"POL-MBR-AUTH-004-02",
				"POL-MBR-AUTH-005-01",
				"POL-MBR-AUTH-005-03",
				"POL-MBR-AUTH-005-07",
			],
			missingPolicyIds: [],
			result: "green",
			handling: "policy-core 기준으로 인증수단, 인증번호, 타이머, 재요청, 실패/제한 상태를 매핑한다.",
		},
		{
			target: "SB external authentication agency failure",
			referencedPolicyIds: [],
			missingPolicyIds: ["AUTH external agency outage / alternative method policy"],
			result: "sb-only",
			handling: "구체적 대체수단 정책은 발명하지 않고 일반 시스템 오류 표면으로만 제한한다.",
		},
	],
	policyRefs: [
		"POL-MBR-AUTH-001-01",
		"POL-MBR-AUTH-002-01",
		"POL-MBR-AUTH-002-05",
		"POL-MBR-AUTH-002-09",
		"POL-MBR-AUTH-003-01",
		"POL-MBR-AUTH-003-03",
		"POL-MBR-AUTH-004-01",
		"POL-MBR-AUTH-004-02",
		"POL-MBR-AUTH-005-01",
		"POL-MBR-AUTH-005-03",
		"POL-MBR-AUTH-005-07",
	],
	ognIds: ["ogn-mbr-auth-select", "ogn-mbr-auth-request"],
	requirements: [
		{
			id: "REQ-MBR-AUTH-SELECT-001",
			ognId: "ogn-mbr-auth-select",
			policyRefs: [
				"POL-MBR-AUTH-002-01",
				"POL-MBR-AUTH-002-05",
				"POL-MBR-AUTH-002-09",
			],
			requirement:
				"본인인증 수단은 휴대폰, PASS, 공동인증서 세 가지를 이 순서로 기본 노출하고 한 가지만 선택한다.",
			userCopy: ["본인인증 수단을 선택해 주세요", "휴대폰", "PASS", "공동인증서"],
			states: ["default", "loading", "load-error"],
		},
		{
			id: "REQ-MBR-AUTH-REQUEST-001",
			ognId: "ogn-mbr-auth-request",
			policyRefs: [
				"POL-MBR-AUTH-001-01",
				"POL-MBR-AUTH-003-01",
				"POL-MBR-AUTH-003-03",
				"POL-MBR-AUTH-004-01",
				"POL-MBR-AUTH-004-02",
				"POL-MBR-AUTH-005-01",
				"POL-MBR-AUTH-005-03",
				"POL-MBR-AUTH-005-07",
			],
			requirement:
				"선택한 인증수단으로 6자리 인증번호를 입력·확인하고, 3분 유효시간, 60초 재요청 쿨다운, 최대 5회 재요청/실패 제한을 안내한다.",
			userCopy: [
				"인증번호 6자리 입력",
				"인증번호 입력",
				"재요청",
				"인증 확인",
				"본인인증 완료하기",
			],
			states: [
				"default",
				"expired",
				"mismatch",
				"blocked",
				"resendCooldown",
				"resendLimit",
				"system",
			],
		},
	],
	caseVariants: [
		{
			id: "NOVA-MBR-FP-003-E1",
			name: "본인인증-인증번호 만료",
			renderMode: "state-variant",
			baseScreenId: "NOVA-MBR-FP-003-0-CX",
			sourceScreenId: "NOVA-MBR-FP-003-0",
			trigger: "authCodeExpired",
			ognId: "ogn-mbr-auth-request",
			policyRefs: ["POL-MBR-AUTH-003-03"],
			missingPolicyRefs: [],
			backendContractIds: ["API-MBR-AUTH-VERIFY-CODE"],
			backendErrorCodes: ["CODE_EXPIRED"],
			uiState: "expired",
			requiredUiChanges: [
				"인증번호 만료 Notice(cautionary)를 노출한다.",
				"인증번호 입력값은 유지하되 인증 확인은 완료 처리하지 않는다.",
				"재요청 action은 정책 쿨다운과 재요청 한도 안에서 복구 수단으로 제공한다.",
				"Bottom CTA는 본인인증 성공 전까지 disabled 상태를 유지한다.",
			],
			recoveryAction: "resendCode",
			followUp: "재발급 안내",
			verificationLevel: "policy-backed-green",
		},
		{
			id: "NOVA-MBR-FP-003-E2",
			name: "본인인증-인증번호 불일치",
			renderMode: "state-variant",
			baseScreenId: "NOVA-MBR-FP-003-0-CX",
			sourceScreenId: "NOVA-MBR-FP-003-0",
			trigger: "authCodeMismatch",
			ognId: "ogn-mbr-auth-request",
			policyRefs: ["POL-MBR-AUTH-005-01", "POL-MBR-AUTH-005-07"],
			missingPolicyRefs: [],
			backendContractIds: ["API-MBR-AUTH-VERIFY-CODE"],
			backendErrorCodes: ["INVALID_CODE"],
			uiState: "mismatch",
			requiredUiChanges: [
				"인증번호 불일치 Notice(negative)를 노출한다.",
				"6자리 재입력 또는 재확인을 허용한다.",
				"실패 횟수와 제한 가능성을 안내 copy에 반영한다.",
				"Bottom CTA는 본인인증 성공 전까지 disabled 상태를 유지한다.",
			],
			recoveryAction: "retryCode",
			followUp: "재시도 또는 제한 처리",
			verificationLevel: "policy-backed-green",
		},
		{
			id: "NOVA-MBR-FP-003-E3",
			name: "본인인증-인증 실패 한도 초과",
			renderMode: "state-variant",
			baseScreenId: "NOVA-MBR-FP-003-0-CX",
			sourceScreenId: "NOVA-MBR-FP-003-0",
			trigger: "authFailureLimitExceeded",
			ognId: "ogn-mbr-auth-request",
			policyRefs: ["POL-MBR-AUTH-005-01", "POL-MBR-AUTH-005-03", "POL-MBR-AUTH-005-07"],
			missingPolicyRefs: [],
			backendContractIds: ["API-MBR-AUTH-VERIFY-CODE"],
			backendErrorCodes: ["AUTH_FAILURE_LIMIT_EXCEEDED"],
			uiState: "blocked",
			requiredUiChanges: [
				"인증 제한 Notice(negative)를 노출한다.",
				"입력 필드, 재요청, 인증 확인 action을 모두 disabled 처리한다.",
				"10분 후 재시도 가능함을 안내한다.",
				"Bottom CTA는 disabled 상태를 유지한다.",
			],
			recoveryAction: "waitUntilUnblocked",
			followUp: "재시도 제한",
			verificationLevel: "policy-backed-green",
		},
		{
			id: "NOVA-MBR-FP-003-E4",
			name: "본인인증-외부 인증기관 오류",
			renderMode: "state-variant",
			baseScreenId: "NOVA-MBR-FP-003-0-CX",
			sourceScreenId: "NOVA-MBR-FP-003-0",
			trigger: "externalAuthProviderError",
			ognId: "ogn-mbr-auth-request",
			policyRefs: [],
			missingPolicyRefs: ["AUTH external agency outage / alternative method policy"],
			backendContractIds: ["API-MBR-AUTH-REQUEST-CODE"],
			backendErrorCodes: ["AUTH_PROVIDER_UNAVAILABLE"],
			uiState: "system",
			requiredUiChanges: [
				"일반 시스템 오류 Notice(negative)를 노출한다.",
				"policy-core에 없는 대체 인증수단 자격, 문구, 라우팅을 발명하지 않는다.",
				"재시도 가능 여부는 backend response와 기존 재요청 정책 범위 안에서만 표현한다.",
				"Bottom CTA는 본인인증 성공 전까지 disabled 상태를 유지한다.",
			],
			recoveryAction: "retryLater",
			followUp: "대체 수단 안내",
			verificationLevel: "sb-only",
		},
	],
	dataRequirements: [
		{
			id: "DATA-MBR-AUTH-METHODS",
			source: "backend",
			entity: "AuthenticationMethodCatalog",
			ognId: "ogn-mbr-auth-select",
			policyRefs: [
				"POL-MBR-AUTH-002-01",
				"POL-MBR-AUTH-002-05",
				"POL-MBR-AUTH-002-09",
			],
			fields: [
				{ name: "methodId", type: "phone | pass | cert", required: true },
				{ name: "label", type: "string", required: true },
				{ name: "enabled", type: "boolean", required: true },
				{ name: "displayOrder", type: "number", required: true },
			],
		},
		{
			id: "DATA-MBR-AUTH-SESSION",
			source: "backend",
			entity: "AuthenticationSession",
			ognId: "ogn-mbr-auth-request",
			policyRefs: [
				"POL-MBR-AUTH-001-01",
				"POL-MBR-AUTH-003-03",
				"POL-MBR-AUTH-004-01",
				"POL-MBR-AUTH-004-02",
				"POL-MBR-AUTH-005-01",
				"POL-MBR-AUTH-005-03",
			],
			fields: [
				{ name: "authSessionId", type: "string", required: true },
				{ name: "expiresAt", type: "datetime", required: true },
				{ name: "resendAvailableAt", type: "datetime", required: true },
				{ name: "resendCount", type: "number", required: true },
				{ name: "failureCount", type: "number", required: true },
				{ name: "blockedUntil", type: "datetime | null", required: false },
			],
		},
	],
	backendContracts: [
		{
			id: "API-MBR-AUTH-METHODS",
			method: "GET",
			path: "/mbr/auth/methods",
			responseSchema: "AuthenticationMethodCatalogResponse",
			errorCodes: ["AUTH_METHODS_UNAVAILABLE"],
			policyRefs: ["POL-MBR-AUTH-002-01", "POL-MBR-AUTH-002-05", "POL-MBR-AUTH-002-09"],
		},
		{
			id: "API-MBR-AUTH-REQUEST-CODE",
			method: "POST",
			path: "/mbr/auth/sessions",
			requestSchema: "CreateAuthenticationSessionRequest",
			responseSchema: "AuthenticationSessionResponse",
			errorCodes: ["RESEND_COOLDOWN", "RESEND_LIMIT_EXCEEDED", "AUTH_PROVIDER_UNAVAILABLE"],
			policyRefs: ["POL-MBR-AUTH-004-01", "POL-MBR-AUTH-004-02"],
		},
		{
			id: "API-MBR-AUTH-VERIFY-CODE",
			method: "POST",
			path: "/mbr/auth/sessions/{authSessionId}/verify",
			requestSchema: "VerifyAuthenticationCodeRequest",
			responseSchema: "VerifyAuthenticationCodeResponse",
			errorCodes: ["INVALID_CODE", "CODE_EXPIRED", "AUTH_FAILURE_LIMIT_EXCEEDED"],
			policyRefs: [
				"POL-MBR-AUTH-001-01",
				"POL-MBR-AUTH-003-01",
				"POL-MBR-AUTH-003-03",
				"POL-MBR-AUTH-005-01",
				"POL-MBR-AUTH-005-03",
				"POL-MBR-AUTH-005-07",
			],
		},
	],
	tableMappings: [
		{
			table: "mbr_auth_session",
			entity: "AuthenticationSession",
			columns: [
				{ column: "auth_session_id", sourceField: "authSessionId", nullable: false },
				{ column: "method_id", sourceField: "methodId", nullable: false },
				{ column: "expires_at", sourceField: "expiresAt", nullable: false },
				{ column: "resend_count", sourceField: "resendCount", nullable: false },
				{ column: "failure_count", sourceField: "failureCount", nullable: false },
				{ column: "blocked_until", sourceField: "blockedUntil", nullable: true },
			],
		},
	],
	governanceRefs: [
		"UXPT_BTN",
		"UXPT_ERR",
		"UXPT_LOD",
		"UXPT_NAV",
		"VOT_RUL",
	],
} as const;
