import type { PreviewComponentRegistryEntry } from "@/utils/component-registry";

export const cxComponentRegistry = [
	{
		id: "status-bar",
		name: "StatusBar",
		layer: "component",
		group: "navigation",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/status-bar",
		status: "active",
	},
	{
		id: "app-bar",
		name: "AppBar",
		layer: "component",
		group: "navigation",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/app-bar",
		status: "active",
	},
	{
		id: "title-main",
		name: "TitleMain",
		layer: "component",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/title-main",
		status: "active",
	},
	{
		id: "title-section",
		name: "TitleSection",
		layer: "component",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/title-section",
		status: "active",
	},
	{
		id: "text",
		name: "Text",
		layer: "atom",
		group: "typography",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/text",
		status: "active",
	},
	{
		id: "text-field",
		name: "TextField",
		layer: "component",
		group: "form",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/text-field",
		status: "active",
	},
	{
		id: "button",
		name: "Button",
		layer: "component",
		group: "action",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/button",
		status: "active",
	},
	{
		id: "action-button",
		name: "ActionButton",
		layer: "pattern",
		group: "action",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/action-button",
		status: "active",
	},
	{
		id: "checkbox",
		name: "Checkbox",
		layer: "component",
		group: "selection",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/checkbox",
		status: "active",
	},
	{
		id: "chips",
		name: "Chips",
		layer: "component",
		group: "selection",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/chips",
		status: "active",
	},
	{
		id: "list-text",
		name: "ListText",
		layer: "component",
		group: "layout",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/list-text",
		status: "active",
	},
	{
		id: "section-item",
		name: "SectionItem",
		layer: "component",
		group: "layout",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/section-item",
		status: "active",
	},
	{
		id: "callout",
		name: "Callout",
		layer: "component",
		group: "feedback",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/callout",
		status: "active",
	},
	{
		id: "search-bar",
		name: "SearchBar",
		layer: "component",
		group: "form",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/search-bar",
		status: "active",
	},
	{
		id: "divider",
		name: "Divider",
		layer: "atom",
		group: "feedback",
		owner: "@pxds/cx-components",
		importPath: "@pxds/cx-components/components/divider",
		status: "active",
	},
] as const satisfies readonly PreviewComponentRegistryEntry[];

export function getCxComponentById(componentId: string) {
	return cxComponentRegistry.find((component) => component.id === componentId);
}
