export const SPEC_KINDS = [
	{
		area: "서비스/UX 원칙 정의 및 관리",
		code: "UXP",
		kind: "uxp",
		name: "가이드라인",
	},
	{
		area: "서비스/UX 원칙 정의 및 관리",
		code: "APP",
		kind: "app",
		name: "공통",
	},
	{
		area: "서비스/UX 원칙 정의 및 관리",
		code: "QLT",
		kind: "qlt",
		name: "품질/적응형",
	},
	{
		area: "전시 구조 및 노출 정책 기획/운영",
		code: "MAIN",
		kind: "main",
		name: "전시 관리 기능",
	},
	{
		area: "전시 구조 및 노출 정책 기획/운영",
		code: "PRDL",
		kind: "prdl",
		name: "상품 목록",
	},
	{
		area: "전시 구조 및 노출 정책 기획/운영",
		code: "BPS",
		kind: "bps",
		name: "외부 BP 서비스 관리 체계",
	},
	{
		area: "AI 기반 탐색·추천 경험 설계",
		code: "SCH",
		kind: "sch",
		name: "AI 검색",
	},
	{
		area: "AI 기반 탐색·추천 경험 설계",
		code: "RCM",
		kind: "rcm",
		name: "개인화/추천",
	},
	{
		area: "AI 기반 탐색·추천 경험 설계",
		code: "ANA",
		kind: "ana",
		name: "데이터 트래킹 체계",
	},
	{
		area: "이벤트 및 멤버십 혜택 관리 체계 기획",
		code: "EVT",
		kind: "evt",
		name: "이벤트",
	},
	{
		area: "이벤트 및 멤버십 혜택 관리 체계 기획",
		code: "CPN",
		kind: "cpn",
		name: "외부 쿠폰",
	},
	{
		area: "이벤트 및 멤버십 혜택 관리 체계 기획",
		code: "MSN",
		kind: "msn",
		name: "미션 프로그램",
	},
	{
		area: "이벤트 및 멤버십 혜택 관리 체계 기획",
		code: "BEN",
		kind: "ben",
		name: "멤버십 혜택",
	},
	{
		area: "이벤트 및 멤버십 혜택 관리 체계 기획",
		code: "TPNT",
		kind: "tpnt",
		name: "T 플러스 포인트",
	},
	{
		area: "상품 및 할인 노출 구조 설계/관리",
		code: "PRDD",
		kind: "prdd",
		name: "상품 상세",
	},
	{
		area: "상품 및 할인 노출 구조 설계/관리",
		code: "CART",
		kind: "cart",
		name: "담기",
	},
	{
		area: "상품 및 할인 노출 구조 설계/관리",
		code: "CARD",
		kind: "card",
		name: "카드/장바구니",
	},
	{
		area: "상품 및 할인 노출 구조 설계/관리",
		code: "SIM",
		kind: "sim",
		name: "할인/시뮬레이션",
	},
	{
		area: "주문·가입 프로세스 설계 및 표준화",
		code: "JOIN",
		kind: "join",
		name: "주문/계약/가입",
	},
	{
		area: "주문·가입 프로세스 설계 및 표준화",
		code: "GFT",
		kind: "gft",
		name: "선물주문",
	},
	{
		area: "주문·가입 프로세스 설계 및 표준화",
		code: "CHG",
		kind: "chg",
		name: "상품변경",
	},
	{
		area: "결제 프로세스 설계 및 결제 수단 관리",
		code: "PAY",
		kind: "pay",
		name: "결제 처리",
	},
	{
		area: "결제 프로세스 설계 및 결제 수단 관리",
		code: "DIS",
		kind: "dis",
		name: "할인 적용",
	},
	{
		area: "결제 프로세스 설계 및 결제 수단 관리",
		code: "PMT",
		kind: "pmt",
		name: "결제 수단",
	},
	{
		area: "주문 관리 기능 기획/운영",
		code: "ORH",
		kind: "orh",
		name: "주문 내역 관리",
	},
	{
		area: "주문 관리 기능 기획/운영",
		code: "DLV",
		kind: "dlv",
		name: "배송/교환/반품",
	},
	{
		area: "주문 관리 기능 기획/운영",
		code: "AUTH",
		kind: "auth",
		name: "상품 연동/인증",
	},
	{
		area: "주문 관리 기능 기획/운영",
		code: "CCL",
		kind: "ccl",
		name: "해지/환불/취소",
	},
	{
		area: "계약 및 가입 정보 관리 체계 기획",
		code: "INFO",
		kind: "info",
		name: "나의 가입 정보",
	},
	{
		area: "계약 및 가입 정보 관리 체계 기획",
		code: "MOD",
		kind: "mod",
		name: "회선 변경/관리",
	},
	{
		area: "계약 및 가입 정보 관리 체계 기획",
		code: "MBS",
		kind: "mbs",
		name: "멤버십 카드 관리",
	},
	{
		area: "요금 조회 및 납부 기능 설계",
		code: "FEE",
		kind: "fee",
		name: "요금 안내서",
	},
	{
		area: "요금 조회 및 납부 기능 설계",
		code: "BIL",
		kind: "bil",
		name: "요금 납부/ 납부 수단 관리",
	},
	{
		area: "요금 조회 및 납부 기능 설계",
		code: "RTB",
		kind: "rtb",
		name: "실시간 이용 요금",
	},
	{
		area: "요금 조회 및 납부 기능 설계",
		code: "BILH",
		kind: "bilh",
		name: "요금 납부 내역",
	},
	{
		area: "요금 조회 및 납부 기능 설계",
		code: "MYPNT",
		kind: "mypnt",
		name: "통합 포인트",
	},
	{
		area: "서비스 및 상품 이용 경험 기획/관리",
		code: "DTC",
		kind: "dtc",
		name: "나의 데이터 및 통화 조회/설정",
	},
	{
		area: "서비스 및 상품 이용 경험 기획/관리",
		code: "DTA",
		kind: "dta",
		name: "데이터/로밍 쿠폰",
	},
	{
		area: "서비스 및 상품 이용 경험 기획/관리",
		code: "MYBEN",
		kind: "myben",
		name: "구독 상품 혜택 공유",
	},
	{
		area: "서비스 및 상품 이용 경험 기획/관리",
		code: "MYCPN",
		kind: "mycpn",
		name: "통합 쿠폰/이용권함",
	},
	{
		area: "회원 및 서비스 환경 설정 기능 설계",
		code: "MBR",
		kind: "mbr",
		name: "회원 가입/탈퇴",
	},
	{
		area: "회원 및 서비스 환경 설정 기능 설계",
		code: "MBI",
		kind: "mbi",
		name: "회원정보 조회/변경",
	},
	{
		area: "회원 및 서비스 환경 설정 기능 설계",
		code: "ALM",
		kind: "alm",
		name: "통합 알림",
	},
	{
		area: "회원 및 서비스 환경 설정 기능 설계",
		code: "AGR",
		kind: "agr",
		name: "통합 약관",
	},
	{
		area: "회원 및 서비스 환경 설정 기능 설계",
		code: "SET",
		kind: "set",
		name: "설정",
	},
	{
		area: "디지털 채널 고객 지원 및 상담 체계 기획",
		code: "CS",
		kind: "cs",
		name: "상담/문의/CS",
	},
	{
		area: "디지털 채널 고객 지원 및 상담 체계 기획",
		code: "GUIDE",
		kind: "guide",
		name: "이용안내/FAQ",
	},
	{
		area: "디지털 채널 고객 지원 및 상담 체계 기획",
		code: "STR",
		kind: "str",
		name: "매장정보",
	},
	{
		area: "디지털 채널 고객 지원 및 상담 체계 기획",
		code: "NTC",
		kind: "ntc",
		name: "공지",
	},
] as const;

export type SpecKind = (typeof SPEC_KINDS)[number];
export type SpecKindArea = SpecKind["area"];
export type SpecKindCode = SpecKind["code"];
export type SpecKindId = SpecKind["kind"];
export type SpecKindName = SpecKind["name"];
